---
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending

categories:
  - title: "🚨 Breaking changes"
    semver-increment: major
    when:
      labels:
        - "breaking-change"
  - title: "✨ New features"
    semver-increment: minor
    when:
      labels:
        - "new-feature"
  - title: "🐛 Bug fixes"
    semver-increment: patch
    when:
      labels:
        - "bugfix"
  - title: "🚀 Enhancements"
    semver-increment: patch
    when:
      labels:
        - "enhancement"
        - "refactor"
        - "performance"
  - title: "🧰 Maintenance"
    semver-increment: patch
    when:
      labels:
        - "maintenance"
        - "ci"
  - title: "📚 Documentation"
    semver-increment: patch
    when:
      labels:
        - "documentation"
  - title: "⬆️ Dependency updates"
    semver-increment: patch
    exclusive: true
    collapse-after: 0
    when:
      labels:
        - "dependencies"
  - type: "version-resolver"
    semver-increment: major
    when:
      label: "major"
  - type: "version-resolver"
    semver-increment: minor
    when:
      label: "minor"
  - type: "version-resolver"
    semver-increment: patch

exclude-contributors:
  - "renovate"

template: |
  ## What’s changed

  $CHANGES

  ## Thanks

  $CONTRIBUTORS
