"""Constants for yalesmartalarmclient"""

YALE_STATE_ARM_FULL = "arm"
YALE_STATE_ARM_PARTIAL = "home"
YALE_STATE_DISARM = "disarm"

YALE_LOCK_STATE_LOCKED = "locked"
YALE_LOCK_STATE_UNLOCKED = "unlocked"
YALE_LOCK_STATE_DOOR_OPEN = "dooropen"
YALE_LOCK_STATE_UNKNOWN = "unknown"

YALE_DOOR_CONTACT_STATE_CLOSED = "closed"
YALE_DOOR_CONTACT_STATE_OPEN = "open"
YALE_DOOR_CONTACT_STATE_UNKNOWN = "unknown"

YALE_CODE_RESULT_SUCCESS = "000"

HOST = "https://mob.yalehomesystem.co.uk/yapi"
ENDPOINT_TOKEN = "/o/token/"
ENDPOINT_SERVICES = "/services/"
YALE_AUTH_TOKEN = "VnVWWDZYVjlXSUNzVHJhcUVpdVNCUHBwZ3ZPakxUeXNsRU1LUHBjdTpkd3RPbE15WEtENUJ5ZW1GWHV0am55eGhrc0U3V0ZFY2p0dFcyOXRaSWNuWHlSWHFsWVBEZ1BSZE1xczF4R3VwVTlxa1o4UE5ubGlQanY5Z2hBZFFtMHpsM0h4V3dlS0ZBcGZzakpMcW1GMm1HR1lXRlpad01MRkw3MGR0bmNndQ=="

YALE_AUTHENTICATION_REFRESH_TOKEN = "refresh_token"
YALE_AUTHENTICATION_ACCESS_TOKEN = "access_token"

DEFAULT_REQUEST_TIMEOUT = 7
MAX_RETRY_SECONDS = 30
MAX_TRIES = 5
